#!/usr/bin/env python3

import sys

from PySide6.QtCore import QSize, Qt
from PySide6.QtWidgets import QApplication, QMainWindow, QLabel, QWidget, QVBoxLayout




class CB_pin(QWidget):
    # def __init__(self, pin_name: str, parent=None):
    #     super().__init__(parent)

    #     self.pin_name = pin_name
    #     self.setMinimumSize(QSize(100, 50))
    #     self.setMaximumSize(QSize(100, 50))
    #     self.setWindowTitle(self.pin_name)

    #     l1 = QLabel()
    #     l1.setText(self.pin_name)
    #     l1.setAlignment(Qt.AlignCenter)

    #     self.setLayout(l1)


def __init__(self, steps=5, *args, **kwargs):
        super().__init__(*args, **kwargs)

        layout = QVBoxLayout()
        self._bar = _Bar()
        layout.addWidget(self._bar)

        # self._dial = QtWidgets.QDial()
        # layout.addWidget(self._dial)

        self.setLayout(layout)




class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setMinimumSize(500, 250)
        self.setWindowTitle("Cybernetics")

        # l1 = QLabel()
        # l1.setText("Hello Cybernetics!")
        # l1.setAlignment(Qt.AlignCenter)

        p1 = CB_pin("TCK")

        # self.setCentralWidget(l1)
        self.setCentralWidget(p1)

if __name__ == "__main__":
    app = QApplication(sys.argv)

    window = MainWindow()
    window.show()

    app.exec()

